jy604/42842.py

https://school.programmers.co.kr/learn/courses/30/lessons/42842

[PGS] 카펫 / Level2 / 42842 / 박정영

---

jaewon/BOJ_1038_감소하는 수.py

문제 풀이 시간 30분(시간초과)
풀이 참고하여 풀었습니다.
https://www.acmicpc.net/problem/1038

[BOJ]감소하는수/Gold5/1038/김재원

---

jaewon/PSG_42747_H-index.py

못풀었습니다 수정이후 업데이트 하겠습니다.
https://school.programmers.co.kr/learn/courses/30/lessons/42747

[PGS] H-Index / Level2 / 42747 / 김재원

---

suhyun/42747.py

https://www.acmicpc.net/problem/42747

[BOJ] 감소하는 수 / 골드5 / 42747-update

---

yoojin/PGS_42583.py

풀이 과정은 다음과 같습니다.
- append할 때마다 시간을 1씩 증가합니다.
(종료되는 시점에서 바로 트럭이 들어가는 게 아니면 문제 조건 상 시간을 1 증가해야 함)
- 더 넣을 수 있는지 확인 후, 공간이 생길 때까지 pop하고 시간을 갱신합니다.
- 이때 큐에 가장 최근에 집어 넣은 트럭의 시간과 현재 가장 빨리 나갈 수 있는(left) 트럭의 시간을 비교합니다. 만약 가장 마지막에 트럭을 넣은 시간이 큰 값이라면, 해당 값에 1을 더해줘야 합니다. - push와 같은 동작입니다.
- 반복문이 종료되면 이제 트럭을 넣을 수 있기 때문에, queue에 새 트럭을 append 해줍니다.
- 남아 있는 트럭에 대해서 가장 마지막으로 append한 시간을 시작 시간으로, 다리를 다 건널 때까지 필요한 시간을 구합니다.

[PGS] 다리를 지나는 트럭 / Level2 / 42583 / 전유진

---

yoojin/PGS_86971.py

https://school.programmers.co.kr/learn/courses/30/lessons/86971

[PGS] 전력망을 둘로 나누기 / Level2 / 86971 / 전유진

---

minseok/전력망을 둘로 나누기_86971.py
minseok/조이스틱_42869.py

완전탐색을 이용한 풀이
https://school.programmers.co.kr/learn/courses/30/lessons/86971

[PGS] 전력망을 둘로 나누기 / level2 / 86971 / 이민석

---

jaewon/PGS_42860_조이스틱.py

40분동안 풀지 못해서 정답을 보고 주석을 다는 형식으로 풀었습니다.
문제 이해를 40분동안 잘못하고 있었음..

[PGS] 조이스틱 / Level2 / 42860 / 김재원

---

suhyun/42860.py
suhyun/43165.py

https://school.programmers.co.kr/learn/courses/30/lessons/42860

[PGS] 조이스틱 / Level2 / 42860 / 지수현

---

suhyun/43165.py

https://school.programmers.co.kr/learn/courses/30/lessons/43165

[PGS] 타겟넘버 / Level2 / 43165 / 지수현

---

yoojin/PGS_42165.py
yoojin/PGS_42860.py

https://school.programmers.co.kr/learn/courses/30/lessons/42165

[PGS] 타겟넘버 / Level2 / 42165 / 전유진

---

jaewon/PGS_42165_타겟넘버.py
jaewon/PGS_42577_전화번호 목록.py

[PGS] 타겟넘버 / level2 / 43165 / 김재원

---

suhyun/42577.py

https://school.programmers.co.kr/learn/courses/30/lessons/42577

[PGS] 전화번호 목록 / level2 / 42577 / 지수현

---

suhyun/42746.py

https://school.programmers.co.kr/learn/courses/30/lessons/42746
틀렸습니돱

[PGS] 가장 큰 수 / Level2 / 42746 / 지수현

---

minseok/가장큰수_42746

https://school.programmers.co.kr/learn/courses/30/lessons/42746#
성공

 [PGS] 가장큰수 / level2 / 43165 / 이민석

---

minseok/구명보트_42885

https://school.programmers.co.kr/learn/courses/30/lessons/42885#
성공

 [PGS] 구명보트 / Level2 / 42885 / 이민석

---

suhyun/42587.py
suhyun/42885.py

[PGS] 구명보트 / Level2 / 42885 / 지수현

---

yoojin/PGS_42839.py
yoojin/PGS_42885.py

https://school.programmers.co.kr/learn/courses/30/lessons/42885

[PGS] 구명보트 / Level2 / 42885 / 전유진

---

jeongyoung/PGS_42885.py

https://school.programmers.co.kr/learn/courses/30/lessons/42885
시간 내 풀이 : ⭕

[PGS] 구명보트 / Level2 / 42885 / 박정영

---

suhyun/42839.py
suhyun/42885.py

[PGS] 소수 찾기 / Level2 / 42839 / 지수현

---

minseok/피로도_87946.py

https://school.programmers.co.kr/learn/courses/30/lessons/87946
푸는데 걸린 시간 : 31분
DFS를 이용해 백트래킹으로 풀었습니다

 [PGS] 피로도/ Level2 / 87946 / 이민석

---

suhyun/87946.py

https://school.programmers.co.kr/learn/courses/30/lessons/87946

[PGS] 피로도 / Level2 / 87946 / 지수현

---

jeongyoung/PGS_42839.py

https://school.programmers.co.kr/learn/courses/30/lessons/42839?language=python3

[PGS] 소수 찾기 / Level2 / 42839 / 박정영

---

suhyun/42584.py

https://www.acmicpc.net/problem/42584

[PGS] 주식가격 / Level2 / 42584 / 지수현

---

jeongyoung/PGS_42584.py

https://school.programmers.co.kr/learn/courses/30/lessons/42584

[PGS] 주식가격 / Level2 / 42584 / 박정영

---

jaewon/정리/PGS_42584_주식가격.py
jaewon/푸는중/PGS_42578_위장.py
jaewon/푸는중/PGS_42584_주식가격.py

[PGS] 주식가격 / Level2 / 42584 / 김재원

---

yoojin/PGS_42584.py

https://school.programmers.co.kr/learn/courses/30/lessons/42584

[PGS] 주식가격 / Level2 / 42584 / 전유진

---

suhyun/1844.py

https://school.programmers.co.kr/learn/courses/30/lessons/1844

[PGS] 게임 맵 최단거리 / Level2 / 1844 / 지수현

---

jeongyoung/PGS_1844.py

https://school.programmers.co.kr/learn/courses/30/lessons/1844  
답 참고

[PGS] 게임 맵 최단거리 / Level2 / 1844 / 박정영

---

jeongyoung/PGS_42578.py

https://school.programmers.co.kr/learn/courses/30/lessons/42578
시간 내 풀이 : ❌

[PGS] 위장 / Level2 / 42578 / 박정영

---

yoojin/PGS_42578.py

https://school.programmers.co.kr/learn/courses/30/lessons/42578

[PGS] 위장 / Level2 / 42578 / 전유진

---

minseok/위장_42578.py

https://school.programmers.co.kr/learn/courses/30/lessons/42578
제한시간 이후 풀이 완료

[PGS] 위장 / Level2 / 42578 / 이민석

---

suhyun/42578.py
suhyun/84512.py

https://school.programmers.co.kr/learn/courses/30/lessons/42578
시간 내 풀이 : ❌

[PGS] 42578 / Level2 / 위장 / 지수현

---

minseok/모음사전_84512.py

https://school.programmers.co.kr/learn/courses/30/lessons/84512
제한시간 이후 풀이 완료

[PGS] 모음사전 / level2 / 84512 / 이민석

---

yoojin/PGS_84512.py

https://school.programmers.co.kr/learn/courses/30/lessons/84512

[PGS] 모음사전 / Level2 / 84512 / 전유진

---

suhyun/84152.py

https://school.programmers.co.kr/learn/courses/30/lessons/84512-rere

[PGS] 모음사전 / Level2 / 84512 / 지수현

---

yoojin/PGS_42626.py
yoojin/PGS_84512.py

https://school.programmers.co.kr/learn/courses/30/lessons/42626

[PGS] 더 맵게 / Level2 / 42626 / 전유진

---

jaewon/정리/PGS_42860_조이스틱.py
jaewon/푸는중/PGS_42626_더 맵게.py
jaewon/푸는중/PGS_84512_모음사전.py

[PGS] 더 맵게 / Level2 / 42626 / 김재원

---

suhyun/42626.py

https://school.programmers.co.kr/learn/courses/30/lessons/42626

[PGS] 더 맵게 / Level2 / 42626 / 지수현

---

jeongyoung/PGS_42626.py

https://school.programmers.co.kr/learn/courses/30/lessons/42626
시간 내 풀이 : ⭕

[PGS] 더 맵게 / Level2 / 42626 / 박정영

---

yoojin/PGS_42883.py

https://school.programmers.co.kr/learn/courses/30/lessons/42883
다 못 풀었음

[PGS] 큰 수 만들기 / Level2 / 42883 / 전유진

---

suhyun/1141.py
suhyun/42883,py

https://www.acmicpc.net/problem/1141
못풀었음

[BOJ] 접두사 / 실버1 / 1141 / 지수현

---

jeongyoung/PGS_42883.py

https://school.programmers.co.kr/learn/courses/30/lessons/42883 
시간 내 풀이 : ❌

[PGS] 큰 수 만들기 / Level2 / 42883 / 박정영-update

---

suhyun/1874.py
suhyun/21317.py

https://www.acmicpc.net/problem/1874

[BOJ] 스택 수열 / 실버2 / 1874 / 지수현

---

yoojin/BOJ_1141.py
yoojin/BOJ_21317.py
yoojin/PGS_42883.py

https://school.programmers.co.kr/learn/courses/30/lessons/1141
시간 내 풀이 실패

[BOJ] 접두사 / 실버1 / 1141 / 전유진

---

suhyun/[PGS] 12900.py

https://school.programmers.co.kr/learn/courses/30/lessons/12900

[PGS] 2 x n 타일링 / Level2 / 12900 / 지수현

---

yoojin/BOJ_21317.py
yoojin/PGS_12900.py

[PGS] 2 x n 타일링 / level2 / 12900 / 전유진

[PGS] 2xn 타일링 / 연습문제 / 12900 / 전유진

---

jeongyoung/PGS_12900.py

https://school.programmers.co.kr/learn/courses/30/lessons/12900 
시간내 풀이 :⭕

[PGS] 2 x n 타일링 / Level2 / 12900 / 박정영

---

minseok/[PGS]2 x n 타일링_12900.py

https://school.programmers.co.kr/learn/courses/30/lessons/12900

[PGS] 2 x n 타일링 / Leve2 / 12900 / 이민석

---

suhyun/[BOJ] 16918.py

https://www.acmicpc.net/problem/16918-re
답보고 작성했음

[BOJ] 봄버맨 / 실버1 / 16918 / 지수현

---

yoojin/BOJ_2477.py

https://www.acmicpc.net/problem/2477

[BOJ] 참외밭 / 실버2 / 2477 / 전유진

---

suhyun/[BOJ] 2477.py

https://www.acmicpc.net/problem/2477

[BOJ] 참외밭 / 실버2 / 2477 /지수현

---

suhyun/[BOJ] 2564.py
suhyun/[PGS]  12981.py

https://www.acmicpc.net/problem/2564

[BOJ] 경비원 / silver1 / 2564 / 지수현

---

yoojin/BOJ_2564.py
yoojin/PGS_12981.py

https://school.programmers.co.kr/learn/courses/30/lessons/12981

[PGS] 영어 끝말잇기 / level2 / 12981 / 전유진

---

suhyun/[PGS] 131127.py

https://school.programmers.co.kr/learn/courses/30/lessons/131127

[PGS] 할인 행사 / level2 / 131127 / 지수현

---

yoojin/PGS_131127.py
yoojin/PGS_43105.py

https://school.programmers.co.kr/learn/courses/30/lessons/131127

[PGS] 할인 행사 / level2 / 131127 / 전유진

---

suhyun/[PGS] 43105.py

https://school.programmers.co.kr/learn/courses/30/lessons/43105

[PGS] 정수 삼각형 / level3 / 43105  / 지수현

---

minseok/[PGS]정수 삼각형_43105.py
minseok/[PGS]할인행사_131127.py

https://school.programmers.co.kr/learn/courses/30/lessons/131127
제한시간 이후 풀이 완료

[PGS] 할인행사/ Leve2 / 131127 +  [PGS] 정수 삼각형 / Leve3 / 43105 / 이민석

---

suhyun/[BOJ] 7562.py

https://www.acmicpc.net/problem/7562

[BOJ] 나이트의 이동 / silver1 / 7562 / 지수현

---

suhyun/[BOJ] 2580.py
suhyun/[BOJ] 7562.py

https://www.acmicpc.net/problem/2580

[BOJ] 스도쿠 / gold4 / 2580 / 지수현

---

yoojin/BOJ_7562.py
yoojin/PGS_43105.py

https://www.acmicpc.net/problem/7562

[BOJ] 나이트의 이동 / 실버1 / 7562 / 전유진

---

minseok/[BOJ}나이트의 이동_7562.py

[BOJ] 나이트의 이동 / silver1 / 7562 / 이민석

---

jeongyoung/BOJ_3020.py
jeongyoung/BOJ_4485.py

https://www.acmicpc.net/problem/3020
시간 내 풀이 : ❌ 완성 코드 아님

[BOJ] 개똥벌레 / Gold 5 / 3020 / 박정영

---

minseok/[BOJ]젤다_4485.py
minseok/[PGS]귤고르기_138476.py

실패
다익스트라 알고리즘 복습 후 블로그 참조하며 풀이 완료

[BOJ] 녹색 옷 입은 애가 젤다지? / Gold 4 / 4485 / 이민석

---

jeongyoung/BOJ_4485.py

https://www.acmicpc.net/problem/4485
시간 내 풀이 : ❌ 답 봄

[BOJ] 녹색 옷 입은 애가 젤다지? / Gold 4 / 4485 / 박정영

---

yoojin/BOJ_4485.py

https://www.acmicpc.net/problem/4485

[BOJ] 녹색 옷 입은 애가 젤다지? / Gold 4 / 4485 / 전유진

---

yoojin/PGS_138476.py

[PGS] 귤 고르기 / level2 / 138476 / 전유진

[PGS] 귤 고르기 / level2 / 138476 / 전유진

---

suhyun/[BOJ] 4485.py
suhyun/[PGS] 138476.py

https://school.programmers.co.kr/learn/courses/30/lessons/138476

[PGS] 귤 고르기 / Level2 / 138476 / 지수현

---

suhyun/[BOJ] 4485.py

https://www.acmicpc.net/problem/4485

[BOJ] 녹색 옷 입은 애가 젤다지? / Gold 4 / 4485 / 지수현

---

PGS_138476.py
jeongyoung/PGS_138476.py

https://school.programmers.co.kr/learn/courses/30/lessons/138476
시간 내 풀이 : ❌

[PGS] 귤 고르기 / Level 2 / 138476 / 박정영

---

yoojin/BOJ_152996.py

https://school.programmers.co.kr/learn/courses/30/lessons/152996

[PGS] 시소 짝꿍 / level2 / 152996 / 전유진

---

suhyun/[PGS] 152996.py

https://school.programmers.co.kr/learn/courses/30/lessons/152996
정영언니 코드 참조

[PGS] 시소 짝꿍 / Level 2 / 152996 / 지수현

---

jeongyoung/PGS_152996.py

https://school.programmers.co.kr/learn/courses/30/lessons/152996
시간 내 풀이 : ⭕

[PGS] 시소 짝꿍 / Level 2 / 152996 / 박정영

---

yoojin/PGS_118667.py

https://school.programmers.co.kr/learn/courses/30/lessons/118667

[PGS] 두 큐 합 같게 만들기 / level2 / 118667 / 전유진

---

suhyun/[BOJ] 12869.py
suhyun/[PGS] 118667.py

https://school.programmers.co.kr/learn/courses/30/lessons/118667

[PGS] 두 큐 합 같게 만들기 / 2022 KAKAO TECH INTERNSHIP / 118667 / 지수현

---

jeongyoung/PGS_118667.py

https://school.programmers.co.kr/learn/courses/30/lessons/118667
시간 내 풀이 : ⭕, 답 봄

[PGS] 두 큐 합 같게 만들기 / Level 2 / 118667 / 박정영

---

yoojin/PGS_92342.py

https://school.programmers.co.kr/learn/courses/30/lessons/92342

[PGS] 양궁대회 / level2 / 92342 / 전유진

---

minseok/[PGS]양궁대회_92342.py

https://school.programmers.co.kr/learn/courses/30/lessons/92342
실패 후 정답코드 참조

 [PGS] 양궁대회 / Leve2 / 92342 / 이민석

---

jeongyoung/PGS_92342.py

https://school.programmers.co.kr/learn/courses/30/lessons/92342
시간 내 풀이 : ❌

[PGS] 양궁대회 / Level 2 / 92342 / 박정영

---

minseok/[PGS]다음 큰 숫자_12911.py

https://school.programmers.co.kr/learn/courses/30/lessons/12911 
**성공**

[PGS] 다음 큰 숫자 / Leve2 / 12911 / 이민석

---

jaewon/푸는중/PGS_12911_다음 큰 숫자.py

https://school.programmers.co.kr/learn/courses/30/lessons/12911

[PGS] 다음 큰 숫자 / Level 2 / 12911 / 김재원

---

jeongyoung/PGS_12911.py

https://school.programmers.co.kr/learn/courses/30/lessons/12911
시간 내 풀이 : ⭕

[PGS] 다음 큰 숫자 / Level 2 / 12911 / 박정영

---

suhyun/[BOJ] 92341.py
suhyun/[PGS] 12911.py
suhyun/[PGS] 92342.py

https://school.programmers.co.kr/learn/courses/30/lessons/12911

[PGS] 다음 큰 숫자 / Level2 / 12911 / 지수현

---

suhyun/[PGS] 12911.py
suhyun/[PGS] 92342.py

https://school.programmers.co.kr/learn/courses/30/lessons/92342

[PGS] 양궁대회 / KAKAO / 92342 / 지수현

---

suhyun/[PGS] 12913.py

https://school.programmers.co.kr/learn/courses/30/lessons/12913

[PGS] 땅따먹기 / Level2 / 12913 / 지수현

---

jaewon/푸는중/BOJ_2343_기타 레슨.py
jaewon/푸는중/PGS_60058_괄호변환.py

https://school.programmers.co.kr/learn/courses/30/lessons/60058

[PGS] 괄호변환 / Level2 / 60058 / 김재원(카카오야 딱기다려~~!)

---

minseok/[PGS]괄호변환_60058.py

[PGS] 괄호 변환 / Leve2 / 60058 / 이민석

---

suhyun/[BOJ] 2343.py

https://www.acmicpc.net/problem/2343

[BOJ] 기타 레슨 / Silver 1 / 2343 / 지수현

---

minseok/[BOJ]기타레슨_2343.py
minseok/[PGS]땅따먹기_12913.py

[BOJ] 기타레슨 / Silver 1 / 2343 / 이민석  + [PGS] 땅따먹기 / level2 / 12913 / 이민석

---

suhyun/[PGS] 60058.py

https://school.programmers.co.kr/learn/courses/30/lessons/60058

[BOJ] 괄호 변환 / Level2 / 60058 / 지수현

---

yoojin/PGS_60058.py

https://school.programmers.co.kr/learn/courses/30/lessons/60058

[PGS] 괄호 변환 / level2 / 60058 / 전유진

---

suhyun/[BOJ] 2075.py
suhyun/[BOJ] 2290.py

https://www.acmicpc.net/problem/2290

[BOJ] LCD Test / Silver2 / 2290 / 지수현

---

yoojin/BOJ_2290.py

https://www.acmicpc.net/problem/2290

[BOJ] LCD Test / Silver2 / 2290 / 전유진

---

jeongyoung/BOJ_2343.py

https://www.acmicpc.net/problem/2343
시간 내 풀이 : ❌, 코드 출처 조머기

[BOJ] 기타 레슨 / Silver 1 / 2343 / 박정영

---

yoojin/BOJ_2304.py

https://www.acmicpc.net/problem/2304

[BOJ] 창고 다각형 / Silver2 / 2304 / 전유진

---

jeongyoung/BOJ_2304.py

https://www.acmicpc.net/problem/2304
시간 내 풀이 : ❌ 아주 쪼금 참고함......

[BOJ] 창고 다각형 / Silver 2 / 2304 / 박정영

---

suhyun/[BOJ] 2304.py

https://www.acmicpc.net/problem/2304

[BOJ] 창고 다각형 / Silver2 / 2304 / 지수현

---

jeongyoung/PGS_135807.py

https://school.programmers.co.kr/learn/courses/30/lessons/135807
시간 내 풀이 : ⭕

[PGS] 숫자 카드 나누기 / Level 2 / 135807 / 박정영

---

suhyun/[PGS] 135807.py
suhyun/[PGS] 64065.py

https://school.programmers.co.kr/learn/courses/30/lessons/135807

[PGS] 숫자 카드 나누기 / Level2 / 135807 / 지수현

---

jaewon/푸는중/PGS_17680_[1차] 캐시.py

https://school.programmers.co.kr/learn/courses/30/lessons/17680
풀었도다

[PGS] 캐시 / Level2 / 17680 / 김재원

---

minseok/[PGS]가장 큰 정사각형 찾기_12905.py
minseok/[PGS]캐시_17680.py

https://school.programmers.co.kr/learn/courses/30/lessons/12905
블로그(https://onlydev.tistory.com/65) 풀이 방법 참고 
캐시 : 성공

 [PGS] 가장 큰 정사각형 찾기 / Leve2 / 12905 + [PGS] 캐시 / Leve2 / 17680 / 이민석

---

yoojin/PGS_17680.py

https://school.programmers.co.kr/learn/courses/30/lessons/17680

[PGS] 캐시 / Level2 / 17680 / 전유진

---

suhyun/[PGS] 12905.py
suhyun/[PGS] 17680.py

https://school.programmers.co.kr/learn/courses/30/lessons/17680

[PGS] 캐시  / Level2 / 17680 / 지수현

---

yoojin/BOJ_1911.py
yoojin/BOJ_2212.py

[BOJ] 전자레인지(B3), 센서(G5), 흙길 보수하기(S1)
